name: Post-Helm3-Values-Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Replace with your preferred runner
    steps:
     - uses: actions/github-script@v7
       id: my-script
       with:
        script: |
          if (currentBuild.changeSets.size() > 0) {
            echo "There are changes, so continue"
            } else {
              echo "No changes, stop the build"
              currentBuild.result = "NOT_BUILT"
              currentBuild.displayName = "#${BUILD_NUMBER} No Changes"
              error "Skipping Build"
            }
              echo "Building Stuff"
