name: Trigger Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        run: echo "Triggering another workflow"
