name: Post-Helm3-Values-Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Replace with your preferred runner
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        run: |
          set -e
          if ! git diff --quiet HEAD master; then
              echo "Changes detected, continue pipeline."
          else
              echo "No changes found, skipping pipeline."
              exit 2  # Set exit code to signal no changes (optional)
          fi
