name: Trigger Workflow

on:
  repository_dispatch:
    #types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Second file
        uses : ./.github/workflows/test/yml
