name: Main Workflow

on:
  workflow_run:
  workflow: ["Foo"]
    types: [completed] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Another Workflow
        run: | echo "sumit"
