name: Main Workflow

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Another Workflow
        run:  echo "sumit"
