name: Main Workflow

on:
  workflow_run:
  workflow: ["Foo"]
    types: [completed] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Another Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MY_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow
          client-payload: '{"key": "value"}'
